# Generated by Django 3.2.4 on 2021-11-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
